/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "eu-central-1:7a5c8414-927a-4508-975c-96f2c5d08ff7",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_RhkgE9Vdk",
    "aws_user_pools_web_client_id": "3mn881r50jnuk6f284n7aq0rp4",
    "oauth": {}
};


export default awsmobile;
