/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e2d0010e-000a-46be-aa33-7108971e2c20",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RuvCVRLeY",
    "aws_user_pools_web_client_id": "1jom3rcvmpkk7ul4fpvkvfgp6f",
    "oauth": {
        "domain": "cloudc7519f0f-c7519f0f-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.d2wcsctjr5vox8.amplifyapp.com/",
        "redirectSignOut": "https://main.d2wcsctjr5vox8.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
